apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: index-mosaic-
  namespace: argo
spec:
  entrypoint: workflow-entrypoint
  serviceAccountName: public-bucket-writer # Staging
  # serviceAccountName: open-data-bucket-writer # Prod
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnWorkflowCompletion
    deleteDelayDuration: 600s
  podMetadata:
    labels:
      app: ls-geomad
    annotations:
      karpenter.sh/do-not-disrupt: "true"
  nodeSelector:
    karpenter.sh/capacity-type: "spot" # Just to be explicit. In dep-terraform, the data-processing nodepool can only pick spot instances
    # TODO: Need to disactivate all dep-specific tags to run non-Pacific processes in another Argo instance.
    dep/workload: data-processing
  tolerations:
    - key: dep/workload
      operator: Equal
      value: data-processing
      effect: NoSchedule
  arguments:
    parameters:
      - name: image-name
        value: "ghcr.io/auspatious/ldn-lulc"
      - name: image-tag
        value: "latest"
      - name: dataset
        # "geomad", or "prediction"
        value: "geomad"
        # value: "prediction"
      - name: region
        # "all", "pacific", or "non-pacific"
        value: "all"

  templates:
    - name: workflow-entrypoint
      dag:
        tasks:
          - name: index-to-stac-geoparquet
            template: index-to-stac-geoparquet

          - name: make-mosaics
            depends: index-to-stac-geoparquet.Succeeded
            template: make-mosaics

    - name: index-to-stac-geoparquet
      activeDeadlineSeconds: 900 # 15 mins
      container:
        image: "{{ workflow.parameters.image-name }}:{{ workflow.parameters.image-tag }}"
        imagePullPolicy: Always
        # imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 2Gi
            cpu: 1
        command: [ldn]
        args:
          - index-to-stac-geoparquet
          - --dataset
          - "{{ workflow.parameters.dataset }}"
          - --region
          - "{{ workflow.parameters.region }}"
        env:
          - name: AWS_WRITE_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: source-coop-creds
                key: aws_access_key_id
          - name: AWS_WRITE_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: source-coop-creds
                key: aws_secret_access_key
          - name: AWS_WRITE_SESSION_TOKEN
            valueFrom:
              secretKeyRef:
                name: source-coop-creds
                key: aws_session_token

    - name: make-mosaics
      activeDeadlineSeconds: 900 # 15 mins
      container:
        image: "{{ workflow.parameters.image-name }}:{{ workflow.parameters.image-tag }}"
        imagePullPolicy: Always
        # imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 2Gi
            cpu: 1
        command: [ldn]
        args:
          - make-mosaics
          - --dataset
          - "{{ workflow.parameters.dataset }}"
        env:
          - name: AWS_WRITE_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: source-coop-creds
                key: aws_access_key_id
          - name: AWS_WRITE_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: source-coop-creds
                key: aws_secret_access_key
          - name: AWS_WRITE_SESSION_TOKEN
            valueFrom:
              secretKeyRef:
                name: source-coop-creds
                key: aws_session_token
