apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: index-
  namespace: argo
spec:
  entrypoint: workflow-entrypoint
  # serviceAccountName: public-bucket-writer # DEP Staging
  serviceAccountName: open-data-bucket-writer # DEP Prod
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnWorkflowCompletion
    deleteDelayDuration: 600s
  podMetadata:
    labels:
      app: ls-geomad
    annotations:
      karpenter.sh/do-not-disrupt: "true"
  # TODO: Need to disactivate all dep-specific tags to run non-Pacific processes in another Argo instance.
  nodeSelector:
    karpenter.sh/capacity-type: "spot" # Just to be explicit. In dep-terraform, the data-processing nodepool can only pick spot instances
    # dep/workload: data-processing # DEP Staging
    dep/workload: data-processing-public # DEP Prod
  tolerations:
    - key: dep/workload
      operator: Equal
      # value: data-processing # DEP Staging
      value: data-processing-public # DEP Prod
      effect: NoSchedule
  arguments:
    parameters:
      - name: image-name
        value: "ghcr.io/auspatious/ldn-lulc"
      - name: image-tag
        value: "latest"
      - name: dataset
        # "geomad", or "lulc"
        value: "geomad"
        # value: "lulc"
      - name: geomad-version # Needed for both datasets because LULC depends on GeoMAD.
        value: "0-3-0"
      - name: lulc-version # Only needed for LULC dataset.
        value: "0-0-4"
      - name: bucket
        # value: "dep-public-staging" # DEP Staging
        value: "dep-public-data" # DEP Prod
      - name: single-region
        value: "--single-region" # For single region products e.g. DEP.
        # value: "--no-single-region" # For places with both regions e.g. Source Coop.
      - name: product-owner
        value: "dep" # required if single-region is true
        # value: None # Leave as None for non-single-region products e.g. Source Coop.
      - name: collection-url-root
        # value: "https://stac.staging.digitalearthpacific.io/collections" # DEP Staging
        value: "https://stac.digitalearthpacific.org/collections" # DEP Prod
        # value: None # For Source Coop, let collection-url-root default.

  templates:
    - name: workflow-entrypoint
      dag:
        tasks:
          - name: index-to-stac-geoparquet
            template: index-to-stac-geoparquet

          # - name: make-geomad-collection
          #   depends: index-to-stac-geoparquet.Succeeded
          #   template: make-geomad-collection

    - name: index-to-stac-geoparquet
      activeDeadlineSeconds: 900 # 15 mins
      container:
        image: "{{ workflow.parameters.image-name }}:{{ workflow.parameters.image-tag }}"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 2Gi
            cpu: 1
        command: [ldn]
        args:
          - index-to-stac-geoparquet
          - --dataset
          - "{{ workflow.parameters.dataset }}"
          - --geomad-version
          - "{{ workflow.parameters.geomad-version }}"
          - --lulc-version
          - "{{ workflow.parameters.lulc-version }}"
          - "{{ workflow.parameters.single-region }}"
          - --product-owner
          - "{{ workflow.parameters.product-owner }}"
          - --bucket
          - "{{ workflow.parameters.bucket }}"

    # Collection already exists for DEP prod so don't need to make it here.

    # - name: make-geomad-collection
    #   activeDeadlineSeconds: 900 # 15 mins
    #   container:
    #     image: "{{ workflow.parameters.image-name }}:{{ workflow.parameters.image-tag }}"
    #     imagePullPolicy: IfNotPresent
    #     resources:
    #       requests:
    #         memory: 2Gi
    #         cpu: 1
    #     command: [ldn]
    #     args:
    #       - create-collection
    #       - --dataset
    #       - "{{ workflow.parameters.dataset }}"
    #       - --geomad-version
    #       - "{{ workflow.parameters.geomad-version }}"
    #       - --lulc-version
    #       - "{{ workflow.parameters.lulc-version }}"
    #       - --product-owner
    #       - "{{ workflow.parameters.product-owner }}"
    #       - --collection-url-root
    #       - "{{ workflow.parameters.collection-url-root }}"
    #       - "{{ workflow.parameters.single-region }}"
    #       - --bucket
    #       - "{{ workflow.parameters.bucket }}"
