apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: landsat-geomad-
  namespace: argo
spec:
  entrypoint: workflow-entrypoint
  serviceAccountName: public-bucket-writer
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnWorkflowCompletion
    deleteDelayDuration: 600s
  parallelism: 50
  podMetadata:
    labels:
      app: ls-geomad
    annotations:
      karpenter.sh/do-not-disrupt: "true"
  nodeSelector:
    karpenter.sh/capacity-type: "spot" # Just to be explicit. In dep-terraform, the data-processing nodepool can only pick spot instances
    # TODO: Need to disactivate all dep-specific tags to run non-Pacific processes in another Argo instance.
    dep/workload: data-processing
  tolerations:
    - key: dep/workload
      operator: Equal
      value: data-processing
      effect: NoSchedule
  arguments:
    parameters:
      - name: version
        value: "0-2-1"
      - name: image-name
        value: "ghcr.io/auspatious/ldn-lulc"
      - name: image-tag
        value: "latest"
      - name: region
        # Just run Pacific in DEP Argo instance.
        value: "pacific" # "all", "pacific", or "non-pacific"
      - name: years
      # TODO: Remove workaround of year subset blocks once the JSON issue is resolved.
        # value: "2000-2008"
        # value: "2009-2016"
        # value: "2017-2025"
        value: "2000-2025"
      - name: overwrite
        value: "--no-overwrite" # Can be "--overwrite" or "--no-overwrite"
      - name: decimated
        value: "--no-decimated" # Can be "--decimated" or "--no-decimated"
  templates:
    - name: workflow-entrypoint
      dag:
        tasks:
          - name: print-tasks
            template: print-tasks

          - name: process-geomad
            depends: print-tasks.Succeeded
            template: process-geomad
            arguments:
              parameters:
                - name: tile-id
                  value: "{{item.id}}"
                - name: year
                  value: "{{item.year}}"
                - name: region
                  value: "{{item.region}}"
            withParam: "{{ tasks.print-tasks.outputs.parameters.tasks }}"


    - name: print-tasks
      activeDeadlineSeconds: 900 # 15 mins
      container:
        image: "{{ workflow.parameters.image-name }}:{{ workflow.parameters.image-tag }}"
        # TODO: Reenable IfNotPresent once image is stable
        # imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            # Requesting a lot of resources for this simple task
            # This is a scheduling trick, if print-tasks requests small, karpenter would
            # provision a small node first (c6.xlarge/large), then process geomad can't fit
            # and has to wait for another node to come up. Not critical, just saves a few minutes
            # of waiting between tasks.
            memory: 16Gi
            cpu: 10
        command: [sh, -c]
        args:
          - |
            ldn print-tasks --years "{{ workflow.parameters.years }}" --region "{{ workflow.parameters.region }}" --version-geomad "{{ workflow.parameters.version }}" --dataset geomad {{ workflow.parameters.overwrite }} > /tmp/tasks.json
      outputs:
        parameters:
          - name: tasks
            valueFrom:
              path: /tmp/tasks.json

    - name: process-geomad
      inputs:
        parameters:
          - name: tile-id
          - name: year
          - name: region
      activeDeadlineSeconds: 1800 # 30 mins
      # Scale resources on retry.
      retryStrategy:
        limit: "1" # Just a single retry.
        # Only retry on killer worker or OOM errors. Error means exit code is unavailable (kubernetes killed the pod).
        expression: >-
          asInt(lastRetry.exitCode) == 42 ||
          asInt(lastRetry.exitCode) == 137 ||
          asInt(lastRetry.exitCode) == 143 ||
          lastRetry.status == "Error"
      # Pod memory needed = (n_workers * memory_limit) + scheduler_overhead + main_process_overhead
      # Pod CPU needed = (n_workers * threads_per_worker) + scheduler_threads
      podSpecPatch: |
        containers:
          - name: main
            resources:
              requests:
                memory: "{{= (asInt(retries) == 0 ? 16 : 32)}}Gi"
                cpu: "{{= (asInt(retries) == 0 ? 10 : 18)}}"
              limits:
                memory: "{{= (asInt(retries) == 0 ? 24 : 48)}}Gi"
                cpu: "{{= (asInt(retries) == 0 ? 12 : 24)}}"
      container:
        image: "{{ workflow.parameters.image-name }}:{{ workflow.parameters.image-tag }}"
        # TODO: Reenable IfNotPresent once image is stable
        # imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        command: [ldn]
        args:
          - geomad
          - run
          - --tile-id
          - "{{ inputs.parameters.tile-id }}"
          - --year
          - "{{ inputs.parameters.year }}"
          - --region
          - "{{ inputs.parameters.region }}"
          - --version
          - "{{ workflow.parameters.version }}"
          - --memory-limit
          - "{{= asInt(retries) == 0 ? '6GB' : '14GB'}}"
          - --n-workers
          - "2"
          - --threads-per-worker
          - "{{= asInt(retries) == 0 ? '4' : '8'}}"
          - --xy-chunk-size
          - "{{= asInt(retries) == 0 ? '800' : '1600'}}"
          - "{{ workflow.parameters.overwrite }}"
          - "{{ workflow.parameters.decimated }}"
