apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: landsat-lulc-classify-
  namespace: argo
spec:
  entrypoint: workflow-entrypoint
  serviceAccountName: public-bucket-writer
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnWorkflowCompletion
    deleteDelayDuration: 600s
  parallelism: 50
  podMetadata:
    labels:
      app: ls-lulc-classify
    annotations:
      karpenter.sh/do-not-disrupt: "true"
  nodeSelector:
    karpenter.sh/capacity-type: "spot"
    # TODO: Need to disactivate all dep-specific tags to run non-Pacific processes in another Argo instance.
    dep/workload: data-processing
  tolerations:
    - key: dep/workload
      operator: Equal
      value: data-processing
      effect: NoSchedule
  arguments:
    parameters:
      - name: image-name
        value: "ghcr.io/auspatious/ldn-lulc"
      - name: image-tag
        value: "latest"
      - name: prediction-version
        value: "0-0-4"
      - name: geomad-version
        value: "0-2-1"
      - name: region
        # Just run Pacific in DEP Argo instance.
        value: "pacific" # "all", "pacific", or "non-pacific"
      - name: years
      # TODO: Remove workaround of year subset blocks once the JSON issue is resolved.
        # value: "2000-2008"
        # value: "2009-2016"
        # value: "2017-2025"
        # value: "2000-2025"
        value: "2025" # Training data is 2020 but predicting on 2025 because there are less gaps than 2020.
      - name: overwrite
        # value: "--overwrite" # Can be "--overwrite" or "--no-overwrite"
        value: "--no-overwrite" # Can be "--overwrite" or "--no-overwrite"
      - name: decimated
        value: "--no-decimated" # Can be "--decimated" or "--no-decimated"
  templates:
    - name: workflow-entrypoint
      dag:
        tasks:
          - name: print-tasks
            template: print-tasks

          - name: classify
            depends: print-tasks.Succeeded
            template: classify
            arguments:
              parameters:
                - name: tile-id
                  value: "{{item.id}}"
                - name: year
                  value: "{{item.year}}"
                - name: region
                  value: "{{item.region}}"
            withParam: "{{ tasks.print-tasks.outputs.parameters.tasks }}"
            # Test a couple of tasks:
            # withParam: '[{"id": "063_020","year": "2025","region": "pacific"},{"id": "077_019","year": "2025","region": "pacific"}]'

    - name: print-tasks
      activeDeadlineSeconds: 900 # 15 mins
      container:
        image: "{{ workflow.parameters.image-name }}:{{ workflow.parameters.image-tag }}"
        imagePullPolicy: IfNotPresent
        resources:
          # Requesting a lot of resources for this simple task
          # This is a scheduling trick, if print-tasks requests small, karpenter would
          # provision a small node first (c6.xlarge/large), then process geomad can't fit
          # and has to wait for another node to come up. Not critical, just saves a few minutes
          # of waiting between tasks.
          requests:
            memory: 8Gi
            cpu: 4
          limits:
            memory: 12Gi
            cpu: 6
        command: [sh, -c]
        args:
          - |
            ldn print-tasks --years "{{ workflow.parameters.years }}" --region "{{ workflow.parameters.region }}" --version-prediction "{{ workflow.parameters.prediction-version }}" --dataset prediction {{ workflow.parameters.overwrite }} > /tmp/tasks.json
      outputs:
        parameters:
          - name: tasks
            valueFrom:
              path: /tmp/tasks.json

    - name: classify
      inputs:
        parameters:
          - name: tile-id
          - name: year
          - name: region
        # 15 minutes is more than enough time for a process to run.
      activeDeadlineSeconds: 900
      # No retries.
      container:
        image: "{{ workflow.parameters.image-name }}:{{ workflow.parameters.image-tag }}"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 8Gi
            cpu: 4
          limits:
            memory: 12Gi
            cpu: 6
        command: [ldn]
        args:
          - classify
          - run
          - --tile-id
          - "{{ inputs.parameters.tile-id }}"
          - --year
          - "{{ inputs.parameters.year }}"
          - --region
          - "{{ inputs.parameters.region }}"
          - --version
          - "{{ workflow.parameters.prediction-version }}"
          - --version-geomad
          - "{{ workflow.parameters.geomad-version }}"
          # Let model_path default
          # - --model-path
          # - "https://s3.us-west-2.amazonaws.com/data.ldn.auspatious.com/models/0-0-4/pacific/2020/lulc_random_forest_model_pacific_2020.joblib"
          - "{{ workflow.parameters.decimated }}"
          - "{{ workflow.parameters.overwrite }}"
          - --memory-limit
          - "10GB"
          - --n-workers
          - "2"
          - --threads-per-worker
          - "4"
          - --xy-chunk-size
          - "1024"
